SEARCH_TERMS = 'Frontend%20developer'
LOCATION = 'United%20States'
GEOID = '103644278' # San Francisco, CA
EXPERIENCE = '3%2C4'
TIMEFRAME = 'r604800' # last week
PP = '102277331'
POSITION = '1'
PAGE_NUM = '0'
JOB_COUNT = 25
regex = '|'
INCLUDE = ['javascript', 'python']
INCLUDE = str(regex.join(INCLUDE))
EXCLUDE = ['degree', 'years']
EXCLUDE = str(regex.join(EXCLUDE))